### ISSUE TITLE
Poster for Android Campaign

### ISSUE THREAD

**Issue by Savio629** [GDSC-FCRIT/Hacktober-Design#1]
## Poster for Android Campaign

For reference: https://www.instagram.com/gdscfcrit/

Resources: https://docs.google.com/presentation/d/1WJmJ2GThCpLunZBxAKJ_xQMJ3JN8Jkp3u7LstEIga0o/edit?pli=1#slide=id.g1e502ea5b07_2_404

**Comment by LighterBund** [comment]
Please assign this task to me

**Comment by gitaditee** [comment]
assign this task  to me please

**Comment by Savio629** [comment]
Updates @LighterBund ?

**Comment by LighterBund** [comment]
working on it, there was some issue will create pr by tomorrow night. sorry for delay
