### ISSUE TITLE
Dussehra poster

### ISSUE THREAD

**Issue by Suhaani07** [GDSC-FCRIT/Hacktober-Design#4]
Will be making a Dussehra poster for Instagram story. Kindly assign this issue.

**Comment by QuantaCoder** [comment]
Saw this design Issue regarding Dusshera Poster, would Like to work on conceptualizing and presenting my creative inputs on the same.
So, Please do me a chance by assigning this issue.

**Comment by DarrenDsouza7273** [comment]
Assigned to you @Suhaani07

**Comment by DarrenDsouza7273** [comment]
Hi @QuantaCoder you can create similar issues for the upcoming festivals/events
